spring:
  application:
    name: authentication
  data:
    mongodb:
      uri: mongodb://localhost:27017/authentication
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
