spring:
  application:
    name: order
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service
server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/