spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order
            uri: lb://order
            predicates:
              - Path=/orders/**
          - id: food
            uri: lb://food
            predicates:
              - Path=/foods/**
          - id: authentication
            uri: lb://authentication
            predicates:
              - Path=/auth/**
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
