spring:
  application:
    name: food
  data:
    mongodb:
      uri: mongodb://localhost:27017/food-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
